import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const digest = bytes => createHash('sha256').update(bytes).digest('hex');

export function validateWebSocketURL(value = '') {
  if (!value) return '';
  let url;
  try { url = new URL(value); } catch { throw new Error('Invalid WebSocket URL'); }
  if (!['ws:', 'wss:'].includes(url.protocol) || url.username || url.password || url.hash || url.search || url.pathname !== '/ws') {
    throw new Error('WebSocket URL must be ws:// or wss:// with /ws and no credentials/query');
  }
  return url.href;
}

// A build captures bytes once. The Node server and exported static site both serve
// this exact asset set, so a worker never caches a mixture while files are edited.
export async function createPwaBuild({ root = projectRoot, wsUrl = '' } = {}) {
  const assets = new Map();
  const add = async (url, file) => assets.set(url, await readFile(path.join(root, file)));
  await add('/', 'index.html');
  await add('/manifest.webmanifest', 'manifest.webmanifest');
  async function walk(directory) {
    for (const item of (await readdir(path.join(root, directory), { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
      const file = `${directory}/${item.name}`;
      if (item.isDirectory()) await walk(file);
      else if (/\.(js|css|svg|png)$/.test(item.name)) await add('/' + file, file);
    }
  }
  for (const dir of ['src', 'shared', 'icons']) await walk(dir);
  await add('/vendor/three.module.js', 'node_modules/three/build/three.module.js');
  await add('/vendor/three.core.js', 'node_modules/three/build/three.core.js');
  await add('/vendor/three.LICENSE.txt', 'node_modules/three/LICENSE');
  assets.set('/runtime-config.js', Buffer.from(`globalThis.RALLY_CONFIG=Object.freeze(${JSON.stringify({ wsUrl: validateWebSocketURL(wsUrl) })});\n`));
  const inventory = [...assets].sort(([a], [b]) => a.localeCompare(b)).map(([url, bytes]) => ({ url, hash: digest(bytes) }));
  const template = await readFile(path.join(root, 'scripts/service-worker.js'), 'utf8');
  const version = digest(JSON.stringify(inventory) + template).slice(0, 16);
  const worker = Buffer.from(`// Generated by scripts/build-pwa.js; do not edit.\nconst VERSION=${JSON.stringify(version)};\nconst ASSETS=${JSON.stringify(inventory)};\n${template}`);
  return { assets, worker, version, inventory };
}

export async function exportPwaBuild(options = {}) {
  const build = await createPwaBuild(options);
  const output = path.resolve(options.root || projectRoot, 'dist');
  for (const [url, body] of [...build.assets, ['/sw.js', build.worker]]) {
    const destination = path.join(output, url === '/' ? 'index.html' : url.slice(1));
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, body);
  }
  await writeFile(path.join(output, '_headers'), '/*\n  Cache-Control: no-cache\n  X-Content-Type-Options: nosniff\n/sw.js\n  Cache-Control: no-cache\n  Service-Worker-Allowed: /\n');
  return build;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const build = await exportPwaBuild({ wsUrl: process.env.PUBLIC_WS_URL || '' });
  console.log(`PWA ${build.version}: ${build.assets.size} local resources exported to dist/`);
}
