import { readFile, readdir, mkdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const digest = bytes => createHash('sha256').update(bytes).digest('hex');

export function validateWebSocketURL(value = '') {
  if (!value) return '';
  let url;
  try { url = new URL(value); } catch { throw new Error('Invalid WebSocket URL'); }
  if (!['ws:', 'wss:'].includes(url.protocol) || url.username || url.password || url.hash || url.search || url.pathname !== '/ws') {
    throw new Error('WebSocket URL must be ws:// or wss:// with /ws and no credentials/query');
  }
  return url.href;
}

export function validateBasePath(value = '/') {
  if (typeof value !== 'string' || !/^\/(?:[A-Za-z0-9_-][A-Za-z0-9._-]*\/)*$/.test(value)) {
    throw new Error('Public base path must be / or a safe absolute directory path ending in /');
  }
  return value;
}

// A build captures bytes once. The Node server and exported static site both serve
// this exact asset set, so a worker never caches a mixture while files are edited.
export async function createPwaBuild({ root = projectRoot, wsUrl = '', basePath = '/', demoMode = false, peerMode = true } = {}) {
  basePath = validateBasePath(basePath);
  if (typeof demoMode !== 'boolean' || demoMode && wsUrl) throw new Error('Demo mode requires a boolean flag and no WebSocket endpoint');
  if (typeof peerMode !== 'boolean') throw new Error('Peer mode requires a boolean flag');
  wsUrl = validateWebSocketURL(wsUrl);
  const assets = new Map();
  const publicURL = url => basePath + url.slice(1);
  const add = async (url, file) => assets.set(publicURL(url), await readFile(path.join(root, file)));
  await add('/', 'index.html');
  const manifest = JSON.parse(await readFile(path.join(root, 'manifest.webmanifest'), 'utf8'));
  manifest.id = basePath; manifest.scope = basePath; manifest.start_url = basePath + '?source=homescreen';
  manifest.icons = manifest.icons.map(icon => ({...icon, src:publicURL(icon.src)}));
  if (peerMode) manifest.description = '人机练习与双手机好友对打，无需电脑；配对需联网，缓存后可离线人机。';
  else if (demoMode) manifest.description = '人机练习，缓存后可离线游玩。';
  assets.set(publicURL('/manifest.webmanifest'), Buffer.from(JSON.stringify(manifest, null, 2) + '\n'));
  async function walk(directory) {
    for (const item of (await readdir(path.join(root, directory), { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
      const file = `${directory}/${item.name}`;
      if (item.isDirectory()) await walk(file);
      else if (/\.(js|css|svg|png)$/.test(item.name) ||
        directory === 'src/audio' && (/\.wav$/.test(item.name) || item.name === 'LICENSE.txt')) await add('/' + file, file);
    }
  }
  for (const dir of ['src', 'shared', 'icons']) await walk(dir);
  await add('/vendor/three.module.js', 'node_modules/three/build/three.module.js');
  await add('/vendor/three.core.js', 'node_modules/three/build/three.core.js');
  await add('/vendor/three.LICENSE.txt', 'node_modules/three/LICENSE');
  await add('/vendor/peerjs.min.js', 'node_modules/peerjs/dist/peerjs.min.js');
  await add('/vendor/peerjs.LICENSE.txt', 'node_modules/peerjs/LICENSE');
  const peerNotices=[];
  for(const [name,file] of [['@msgpack/msgpack','LICENSE'],['eventemitter3','LICENSE'],['peerjs-js-binarypack','LICENSE'],['webrtc-adapter','LICENSE.md'],['sdp','LICENSE']])
    peerNotices.push(`${name}\n\n${await readFile(path.join(root,'node_modules',name,file),'utf8')}`);
  assets.set(publicURL('/vendor/peerjs-dependencies.LICENSE.txt'),Buffer.from(peerNotices.join('\n\n---\n\n')));
  assets.set(publicURL('/runtime-config.js'), Buffer.from(`globalThis.RALLY_CONFIG=Object.freeze(${JSON.stringify({ wsUrl, basePath, demoMode, peerMode })});\n`));
  const inventory = [...assets].sort(([a], [b]) => a.localeCompare(b)).map(([url, bytes]) => ({ url, hash: digest(bytes) }));
  const template = await readFile(path.join(root, 'scripts/service-worker.js'), 'utf8');
  const version = digest(JSON.stringify(inventory) + template).slice(0, 16);
  const cachePrefix = 'rally-assets-' + encodeURIComponent(basePath) + '-';
  const worker = Buffer.from(`// Generated by scripts/build-pwa.js; do not edit.\nconst VERSION=${JSON.stringify(version)};\nconst BASE_PATH=${JSON.stringify(basePath)};\nconst CACHE_PREFIX=${JSON.stringify(cachePrefix)};\nconst ASSETS=${JSON.stringify(inventory)};\n${template}`);
  return { assets, worker, version, inventory, basePath, cachePrefix };
}

export async function exportPwaBuild(options = {}) {
  const build = await createPwaBuild(options);
  const output = options.outputDir ? path.resolve(options.outputDir) : path.resolve(options.root || projectRoot, 'dist');
  for (const [url, body] of [...build.assets, [build.basePath + 'sw.js', build.worker]]) {
    const destination = path.join(output, url === build.basePath ? 'index.html' : url.slice(build.basePath.length));
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, body);
  }
  await writeFile(path.join(output, '_headers'), `/*\n  Cache-Control: no-cache\n  X-Content-Type-Options: nosniff\n${build.basePath}sw.js\n  Cache-Control: no-cache\n  Service-Worker-Allowed: ${build.basePath}\n`);
  await writeFile(path.join(output, '.nojekyll'), '');
  return build;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const build = await exportPwaBuild({ wsUrl: process.env.PUBLIC_WS_URL || '', basePath: process.env.PUBLIC_BASE_PATH || '/', demoMode: process.env.PUBLIC_DEMO_MODE === '1', peerMode: process.env.PUBLIC_PEER_MODE !== '0' });
  console.log(`PWA ${build.version}: ${build.assets.size} local resources exported to dist/`);
}
