import * as THREE from 'three';

const TAU = Math.PI * 2;
const FACE_Y = .54, HOOP_X = .1065, HOOP_Y = .1335;

function paint(geometry, color) {
  const positions = geometry.attributes.position, colors = [];
  for (let i = 0; i < positions.count; i++) {
    const value = typeof color === 'function' ? color(positions.getX(i), positions.getY(i)) : color;
    const rgb = new THREE.Color(value);
    colors.push(rgb.r, rgb.g, rgb.b);
  }
  geometry.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
  return geometry;
}

// Parts share one material per surface type; construction geometries are
// released after copying instead of becoming additional scene objects.
function merge(parts) {
  const geometry = new THREE.BufferGeometry(), indices = [], attributes = { position: [], normal: [], color: [] };
  let offset = 0;
  for (const part of parts) {
    for (const name of Object.keys(attributes)) attributes[name].push(...part.attributes[name].array);
    for (const index of part.index.array) indices.push(index + offset);
    offset += part.attributes.position.count;
    part.dispose();
  }
  for (const [name, array] of Object.entries(attributes)) geometry.setAttribute(name, new THREE.Float32BufferAttribute(array, 3));
  geometry.setIndex(indices);
  geometry.computeBoundingBox(); geometry.computeBoundingSphere();
  return geometry;
}

function cylinder(bottom, top, radiusBottom, radiusTop, color, sides = 8) {
  const start = new THREE.Vector3(...bottom), end = new THREE.Vector3(...top), direction = end.clone().sub(start);
  const geometry = new THREE.CylinderGeometry(radiusTop, radiusBottom, direction.length(), sides);
  geometry.applyQuaternion(new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, 1, 0), direction.normalize()));
  geometry.translate(...start.add(end).multiplyScalar(.5).toArray());
  return paint(geometry, color);
}

function hoopGeometry(dark, white, accent) {
  const positions = [], indices = [], segments = 48, sides = 6;
  // A bevelled beam has a consistent radial thickness and a shallower depth.
  // Its outer dimensions are .224 x .278, centred on the gameplay contact.
  for (let i = 0; i < segments; i++) {
    const angle = i / segments * TAU, c = Math.cos(angle), s = Math.sin(angle);
    const normal = new THREE.Vector2(c / HOOP_X, s / HOOP_Y).normalize();
    for (let j = 0; j < sides; j++) {
      const section = j / sides * TAU, radial = Math.cos(section) * .0055;
      positions.push(HOOP_X * c + normal.x * radial, FACE_Y + HOOP_Y * s + normal.y * radial, Math.sin(section) * .0048);
      const a = i * sides + j, b = i * sides + (j + 1) % sides;
      const next = ((i + 1) % segments) * sides;
      indices.push(a, next + j, b, b, next + j, next + (j + 1) % sides);
    }
  }
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3));
  geometry.setIndex(indices); geometry.computeVertexNormals();
  return paint(geometry, (x, y) => {
    const relativeY = Math.abs(y - FACE_Y);
    if (relativeY > .087 && relativeY < .104) return white;
    return y > FACE_Y + .104 || Math.abs(x) > .075 ? accent : dark;
  });
}

/** Visual only: the grip starts at zero, points along +Y, and the face centre
 * remains (0, .54, 0). No collision or timing data is generated by this model. */
export function makeRacket({ dark = 0x16313d, white = 0xf0f0df, accent = 0xffd69b } = {}) {
  const group = new THREE.Group(); group.name = 'racket';
  const frameParts = [hoopGeometry(dark, white, accent),
    cylinder([0, .143, 0], [0, .377, 0], .004, .0033, white),
    cylinder([0, .135, 0], [0, .153, 0], .011, .004, dark),
    cylinder([0, .174, 0], [0, .186, 0], .0041, .0041, accent),
    cylinder([0, .357, 0], [0, .379, 0], .004, .004, dark)
  ];
  for (const sign of [-1, 1]) frameParts.push(
    cylinder([0, .373, 0], [sign * .035, .414, 0], .0038, .0045, accent, 6)
  );
  // Small black sleeves read as grommets on the front and rear of the frame.
  for (let i = 0; i < 24; i++) {
    const angle = (i + .5) / 24 * TAU;
    const sleeve = new THREE.BoxGeometry(.003, .006, .0105);
    sleeve.rotateZ(angle);
    sleeve.translate(HOOP_X * Math.cos(angle), FACE_Y + HOOP_Y * Math.sin(angle), 0);
    frameParts.push(paint(sleeve, dark));
  }
  const gripParts = [
    cylinder([0, .007, 0], [0, .14, 0], .014, .0125, dark),
    cylinder([0, 0, 0], [0, .007, 0], .017, .016, accent),
    cylinder([0, .007, 0], [0, .012, 0], .016, .014, dark),
    cylinder([0, .132, 0], [0, .14, 0], .0132, .0132, accent)
  ];
  const winding = [];
  for (let i = 0; i <= 64; i++) {
    const t = i / 64, angle = t * TAU * 7, radius = .014 - t * .0015;
    winding.push(new THREE.Vector3(Math.cos(angle) * radius, .014 + t * .116, Math.sin(angle) * radius));
  }
  gripParts.push(paint(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(winding), 64, .00045, 3, false),
    new THREE.Color(dark).lerp(new THREE.Color(white), .24)));

  const frame = new THREE.Mesh(merge(frameParts), new THREE.MeshStandardMaterial({ vertexColors: true, roughness: .43, metalness: .12 }));
  frame.name = 'racket-frame'; frame.castShadow = true; frame.receiveShadow = true;
  const grip = new THREE.Mesh(merge(gripParts), new THREE.MeshStandardMaterial({ vertexColors: true, roughness: .9 }));
  grip.name = 'racket-grip'; grip.castShadow = true; grip.receiveShadow = true;

  const points = [], radiusX = .101, radiusY = .128;
  for (let i = -8; i <= 8; i++) {
    const x = i * .012, half = radiusY * Math.sqrt(1 - (x / radiusX) ** 2);
    points.push(x, FACE_Y - half, .0003, x, FACE_Y + half, .0003);
  }
  for (let i = -10; i <= 10; i++) {
    const y = i * .012, half = radiusX * Math.sqrt(1 - (y / radiusY) ** 2);
    points.push(-half, FACE_Y + y, -.0003, half, FACE_Y + y, -.0003);
  }
  const stringGeometry = new THREE.BufferGeometry();
  stringGeometry.setAttribute('position', new THREE.Float32BufferAttribute(points, 3));
  const strings = new THREE.LineSegments(stringGeometry, new THREE.LineBasicMaterial({ color: white, transparent: true, opacity: .78 }));
  strings.name = 'racket-strings';
  group.add(frame, grip, strings);

  let disposed = false;
  group.dispose = () => {
    if (disposed) return;
    disposed = true;
    for (const object of [frame, grip, strings]) { object.geometry.dispose(); object.material.dispose(); }
  };
  return group;
}
